---
- name: Attach contracts to EPGs
  hosts: apic
  connection: local
  gather_facts: no
  vars:
    tenant_name: ansible
    vrfs:
      - development
      - testing
      - acceptance
      - production
    ap_name: webshop
    epg_names:
      - web
      - app
      - db

  tasks:
  - name: Attach provided contract to EPGs
    aci_epg_to_contract:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      contract_type: provider
      contract: 'ctrct_{{ item.1 }}'
      epg: 'epg_{{ item.1 }}'
      ap: 'ap_{{ ap_name }}_{{ item.0 }}'
      tenant: 'tn_{{ tenant_name }}'
    with_nested:
      - '{{ vrfs }}'
      - '{{ epg_names }}'

  - name: Attach consumed contracts to web EPGs
    aci_epg_to_contract:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      contract_type: consumer
      contract: 'ctrct_{{ epg_names.1 }}'
      epg: 'epg_{{ epg_names.0 }}'
      ap: 'ap_{{ ap_name }}_{{ item }}'
      tenant: 'tn_{{ tenant_name }}'
    with_items:
      - '{{ vrfs }}'

  - name: Attach consumed contracts to app EPGs
    aci_epg_to_contract:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      contract_type: consumer
      contract: 'ctrct_{{ epg_names.2 }}'
      epg: 'epg_{{ epg_names.1 }}'
      ap: 'ap_{{ ap_name }}_{{ item }}'
      tenant: 'tn_{{ tenant_name }}'
    with_items:
      - '{{ vrfs }}'
