- name: Create a snapshot before deployment
  hosts: apic
  connection: local
  gather_facts: no
  collections:
    - cisco.aci
 
  tasks:
  - name: Create a snapshot before deployment
    aci_config_snapshot:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      export_policy: AnsibleSnapshots
      format: xml
      max_count: 10
      description: Snapshot created by Ansible
