---
- name: Create a reference tenant with a predefined structure
  hosts: apic
  connection: local
  gather_facts: no
  vars:
    tenant_name: Ansible

  tasks:
  - name: Add the tenant
    aci_tenant:
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      tenant: '{{ tenant_name }}'
      description: Tenant created by Ansible
    delegate_to: localhost