---
- name: Gather serial numbers of hardware components
  hosts: apic
  connection: local
  gather_facts: no
  collections:
    - cisco.aci

  tasks:
  - name: Get fabric nodes
    aci_rest:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      method: get
      path: /api/node/class/fabricNode.json
    register: nodes_result
  
  - name: Create node list data structure and add keys
    set_fact:
      nodes: "{{ nodes | default([]) + [{ 'dn': item.fabricNode.attributes.dn,
                                          'serial': item.fabricNode.attributes.serial,
                                          'name': item.fabricNode.attributes.name }] }}"
    loop: '{{ nodes_result.imdata}}'

  - name: Print node list
    debug:
      var: nodes

  - name: Get power supplies
    aci_rest:
      hostname: '{{ inventory_hostname }}'
      username: '{{ script_user }}'
      private_key: '{{ keyfile }}'
      validate_certs: no
      method: get
      path: '/api/node/mo/{{ item.dn }}/sys/ch.json?rsp-subtree=full&rsp-subtree-class=eqptPsu'
    loop: '{{ nodes }}'
    register: ps_results

  - name: Print results
    debug:
      var: item
    loop: '{{ ps_results.results }}'
 
