---
- name: Register leaf and spine switches
  hosts: apic
  connection: local
  gather_facts: no
  vars:
    fabric_switches:
      - name: Leaf-1
        nodeid: 101
        serial: TEP-1-101
      - name: Leaf-2
        nodeid: 102
        serial: TEP-1-102
      - name: Spine-1
        nodeid: 111
        serial: TEP-1-103

  tasks:
  - name: Register leaf and spine switches
    aci_rest:
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      validate_certs: no
      method: post
      path: /api/mo/uni/controller/nodeidentpol.json
      content:
        fabricNodeIdentP:
          attributes:
            name: '{{ item.name }}'
            nodeId: '{{ item.nodeid }}'
            serial: '{{ item.serial }}'
    with_items:
      - '{{ fabric_switches }}'
    delegate_to: localhost
