---
# file: roles/tenants/tasks/network.yml

- name: Create the VRFs
  aci_vrf:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    vrf: 'vrf_{{ item }}'
    tenant: 'tn_{{ tenant_name }}'
  with_items:
    - '{{ vrfs }}'

- name: Create the bridge domains
  aci_bd:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    bd: 'bd_{{ item.0 }}_{{ item.1.name }}'
    vrf: 'vrf_{{ item.0 }}'
    tenant: 'tn_{{ tenant_name }}'
  with_nested:
    - '{{ vrfs }}'
    - '{{ bd_names_and_subnets}}'

- name: Attach the subnets to bridge domains
  aci_bd_subnet:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    gateway: '{{ item.1.gateway }}'
    mask: '{{ item.1.mask }}'
    bd: 'bd_{{ item.0 }}_{{ item.1.name }}'
    tenant: 'tn_{{ tenant_name }}'
  with_nested:
    - '{{ vrfs }}'
    - '{{ bd_names_and_subnets}}'
