---
# file: roles/tenants/vars/main.yml

tenant_name: layer_zero

vrfs:
  - development
  - testing
  - acceptance
  - production

bd_names_and_subnets:
  - name: frontend
    gateway: 172.16.1.254
    mask: 24 
  - name: backend
    gateway: 172.16.2.254
    mask: 24 

ap_name: webshop

frontend_epgs:
  - web
backend_epgs:
  - app
  - db

contract_names_and_ports:
  - name: web
    ports:
      - 80
      - 443
  - name: app
    ports:
      - 8080
  - name: db
    ports:
      - 1433

initial_vlan: 1000

vpcs:
  - leafs: 101-102
    device: ucs-fi-a
  - leafs: 101-102
    device: ucs-fi-b
