---
# file: roles/fabric/tasks/main.yml

- name: Register leaf and spine switches
  when: env is defined
  aci_rest:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    method: post
    path: /api/mo/uni/controller/nodeidentpol.json
    content:
      fabricNodeIdentP:
        attributes:
          name: '{{ item.name }}'
          nodeId: '{{ item.nodeid }}'
          serial: '{{ item.serial }}'
  with_items:
    - '{{ fabric_switches[env] }}'

- name: Create VLAN pool for bare metal servers
  aci_vlan_pool:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'phys_bare_metal'
    mode: static

- name: Add VLANs to bare metal VLAN pool
  aci_vlan_pool_encap_block:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: '{{ bare_metal_vlans.start }}-{{ bare_metal_vlans.end }}'
    pool: 'phys_bare_metal'
    pool_mode: static
    mode: inherit
    start: '{{ bare_metal_vlans.start }}'
    end: '{{ bare_metal_vlans.end }}'

- name: Create physical domain for bare metal servers
  aci_domain:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: dom_bare_metal
    domain_type: phys

- name: Add VLAN pool to physical domain
  aci_domain_to_vlan_pool:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    domain: dom_bare_metal
    domain_type: phys
    pool: phys_bare_metal
    pool_allocation_mode: static

- name: Create attachable access entity profile for bare metal servers
  aci_aep:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: aep_bare_metal

- name: Attach physical domain to attachable entity profile
  aci_aep_to_domain:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    aep: aep_bare_metal
    domain: dom_bare_metal
    domain_type: phys

- name: Create policy to disable LLDP
  aci_interface_policy_lldp:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: ifpol_lldp_off
    receive_state: no
    transmit_state: no

- name: Create policy to enable CDP
  aci_rest:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    method: post
    path: '/api/mo/uni/infra.json'
    content:
      cdpIfPol:
        attributes:
          name: ifpol_cdp_on
          adminSt: enabled

- name: Create port-channel policy to enable LACP
  aci_interface_policy_port_channel:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: ifpol_lacp_active
    mode: active

- name: Create vPC domains
  aci_switch_policy_vpc_protection_group:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'vpc_dom_{{item.id}}'
    id: '{{ item.id }}'
    switch_1_id: '{{ item.switch_1 }}'
    switch_2_id: '{{ item.switch_2 }}'
  with_items:
    - '{{ vpc_domains }}'

- name: Create leaf profiles for vPC pairs
  aci_switch_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'swp_leaf_pair_{{ item.switch_1 }}_{{ item.switch_2 }}'
  with_items:
    - '{{ vpc_domains }}'

- name: Attach leaf-selector to leaf profiles
  aci_switch_leaf_selector:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    leaf: '{{ item.switch_1 }}-{{ item.switch_2 }}'
    leaf_node_blk: '{{ item.switch_1 }}-{{ item.switch_2 }}'
    leaf_profile: 'swp_leaf_pair_{{ item.switch_1 }}_{{ item.switch_2 }}'
    from: '{{ item.switch_1 }}'
    to: '{{ item.switch_2 }}'
  with_items:
    - '{{ vpc_domains }}'

- name: Create interface profiles for vPC pairs
  aci_interface_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'ifp_leaf_pair_{{ item.switch_1 }}_{{ item.switch_2 }}'
  with_items:
    - '{{ vpc_domains }}'

- name: Attach interface profiles to switch profiles for vPC pairs
  aci_interface_selector_to_switch_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    interface_profile_name: 'ifp_leaf_pair_{{ item.switch_1 }}_{{ item.switch_2 }}'
    leaf_profile: 'swp_leaf_pair_{{ item.switch_1 }}_{{ item.switch_2 }}'
  with_items:
    - '{{ vpc_domains }}'

- name: Create leaf profiles for individual switches
  aci_switch_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'swp_leaf_switch_{{ item }}'
  with_items:
    - '{{ leaf_switches }}'

- name: Attach leaf-selector to leaf profiles
  aci_switch_leaf_selector:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    leaf: '{{ item }}'
    leaf_node_blk: '{{ item }}'
    leaf_profile: 'swp_leaf_switch_{{ item }}'
    from: '{{ item }}'
    to: '{{ item }}'
  with_items:
    - '{{ leaf_switches }}'

- name: Create interface profiles for individual switches
  aci_interface_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    name: 'ifp_leaf_switch_{{ item }}'
  with_items:
    - '{{ leaf_switches }}'

- name: Attach interface profiles to switch profiles for individual switches
  aci_interface_selector_to_switch_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    interface_profile_name: 'ifp_leaf_switch_{{ item }}'
    leaf_profile: 'swp_leaf_switch_{{ item }}'
  with_items:
    - '{{ leaf_switches }}'

- name: Create vPC policy groups
  aci_interface_policy_leaf_policy_group:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    lag_type: node
    policy_group: 'ipg_vpc_{{ item.device_name }}'
    description: 'vPC to {{ item.device_name }}'
    aep: aep_bare_metal
    cdp_policy: ifpol_cdp_on
    lldp_policy: ifpol_lldp_off
    port_channel_policy: ifpol_lacp_active
  with_items:
    - '{{ vpcs }}'

- name: Attach ports to vPC interface profiles
  aci_access_port_to_interface_policy_leaf_profile:
    hostname: '{{ inventory_hostname }}'
    username: '{{ script_user }}'
    private_key: '{{ keyfile }}'
    validate_certs: no
    leaf_interface_profile: 'ifp_leaf_pair_{{ item.0.pair.0 }}_{{ item.0.pair.1 }}'
    policy_group: 'ipg_vpc_{{ item.0.device_name }}'
    interface_type: vpc
    leaf_port_blk: 'port_{{ item.1 }}'
    access_port_selector: 'port_{{ item.1 }}'
    from_port: '{{ item.1 }}'
    to_port: '{{ item.1 }}'
  with_subelements:
    - '{{ vpcs }}'
    -  ports
